"""UNITI regex services backed exclusively by the third-party regex package."""

from .analysis import (
    AnalysisState,
    DiagnosticSeverity,
    ExpressionRole,
    GroupIdentity,
    InlineSwitch,
    MAX_EXPRESSION_CHARS,
    PatternStructure,
    RegexAnalysis,
    RegexDiagnostic,
    RegexToken,
    TokenPair,
    analyze_pattern,
    analyze_replacement,
    pending_pattern_analysis,
)
from .captures import (
    MAX_CAPTURE_CONTEXT_CHARS,
    MAX_CAPTURE_PREVIEWS,
    MAX_CAPTURE_PREVIEW_CHARS,
    MAX_CAPTURE_REPORT_BYTES,
    CaptureGroupRow,
    CaptureMatchReport,
    CapturePreview,
    CaptureReport,
    CaptureReportRequest,
    resolve_capture_report,
)
from .replacement_plan import (
    Replacement,
    ReplacementPlan,
    ReplacementPlanEstimate,
    ReplacementPlanLimitError,
)

__all__ = [
    "AnalysisState",
    "DiagnosticSeverity",
    "ExpressionRole",
    "GroupIdentity",
    "InlineSwitch",
    "MAX_EXPRESSION_CHARS",
    "MAX_CAPTURE_CONTEXT_CHARS",
    "MAX_CAPTURE_PREVIEWS",
    "MAX_CAPTURE_PREVIEW_CHARS",
    "MAX_CAPTURE_REPORT_BYTES",
    "PatternStructure",
    "RegexAnalysis",
    "RegexDiagnostic",
    "RegexToken",
    "CaptureGroupRow",
    "CaptureMatchReport",
    "CapturePreview",
    "CaptureReport",
    "CaptureReportRequest",
    "Replacement",
    "ReplacementPlan",
    "ReplacementPlanEstimate",
    "ReplacementPlanLimitError",
    "TokenPair",
    "analyze_pattern",
    "analyze_replacement",
    "pending_pattern_analysis",
    "resolve_capture_report",
]
