"""Qt-independent resource and worker services for UNITI."""

from .cache import CacheManager, CachePriority
from .cancel import CancellationToken, WorkCancelled
from .manager import ResourceManager, ResourceStatus
from .memory import (
    MemorySnapshot,
    PressureState,
    automatic_cache_target,
    current_process_handle_count,
    pressure_state,
    probe_memory,
    release_unused_heap_pages,
)
from .policy import (
    ComparisonLimits,
    GateLimit,
    HostRequirement,
    PerformancePolicy,
    PressureLimits,
    ResourceLimits,
    ResourceState,
    TierPolicy,
    classify_resource_state,
    load_performance_policy,
)
from .telemetry import (
    HostResourceProfile,
    PlatformIdentity,
    ResourceSampler,
    ResourceSnapshot,
    current_process_rss_bytes,
    peak_process_rss_bytes,
    probe_host_profile,
    probe_platform_identity,
)
from .tasks import (
    LatestTaskSlot,
    TaskAdmissionError,
    TaskContext,
    TaskCoordinator,
    TaskHandle,
    TaskKind,
    TaskProgress,
    TaskSnapshot,
    TaskSpec,
    TaskState,
    TaskSystemSnapshot,
)
from .workers import PriorityWorkerPool, WorkPriority

__all__ = [
    "CacheManager",
    "CachePriority",
    "CancellationToken",
    "ComparisonLimits",
    "GateLimit",
    "HostRequirement",
    "HostResourceProfile",
    "PlatformIdentity",
    "MemorySnapshot",
    "LatestTaskSlot",
    "PerformancePolicy",
    "PressureState",
    "PressureLimits",
    "ResourceManager",
    "ResourceStatus",
    "ResourceLimits",
    "ResourceSampler",
    "ResourceSnapshot",
    "ResourceState",
    "PriorityWorkerPool",
    "TierPolicy",
    "TaskAdmissionError",
    "TaskContext",
    "TaskCoordinator",
    "TaskHandle",
    "TaskKind",
    "TaskProgress",
    "TaskSnapshot",
    "TaskSpec",
    "TaskState",
    "TaskSystemSnapshot",
    "WorkCancelled",
    "WorkPriority",
    "automatic_cache_target",
    "classify_resource_state",
    "current_process_handle_count",
    "current_process_rss_bytes",
    "load_performance_policy",
    "peak_process_rss_bytes",
    "pressure_state",
    "probe_host_profile",
    "probe_platform_identity",
    "probe_memory",
    "release_unused_heap_pages",
]
